#include "arcana/profile.hpp"
#include "arcana/data.hpp"
#include <fstream>
#include <sstream>
namespace arcana { namespace {
const std::unordered_map<std::string,std::vector<int>>& costs(){static const std::unordered_map<std::string,std::vector<int>> c={
{"vigor",{40,90,160,250,360}},{"might",{50,110,190,290,420}},{"celerity",{70,150,260,400}},{"stride",{45,110,200}},{"ward",{60,130,230,360}},{"reach",{30,70,130}},{"wisdom",{45,100,170,260,380}},{"greed",{60,140,260}},{"channel",{55,130,240}},{"reroll",{80,180,320}},{"pact",{450}},{"phoenix",{600}},{"arsenal",{300}},{"secondSpell",{400}},{"endless",{500}}};return c;}
std::vector<std::string> split(const std::string&s,char d){std::vector<std::string>o;std::stringstream ss(s);std::string x;while(std::getline(ss,x,d))if(!x.empty())o.push_back(x);return o;}
}
Profile loadProfile(const std::string&path){Profile p;std::ifstream f(path);std::string line;while(std::getline(f,line)){auto at=line.find('=');if(at==std::string::npos)continue;auto k=line.substr(0,at),v=line.substr(at+1);try{if(k=="coins")p.coins=std::max(0,std::stoi(v));else if(k=="invested")p.invested=std::max(0,std::stoi(v));else if(k.rfind("upgrade.",0)==0){auto id=k.substr(8);auto ci=costs().find(id);if(ci!=costs().end())p.upgrades.rank[id]=std::clamp(std::stoi(v),0,(int)ci->second.size());}else if(k.rfind("codex.",0)==0){auto sec=k.substr(6);for(auto&id:split(v,','))p.codex[sec].insert(id);}else if(k=="daily.key")p.daily.key=v;else if(k=="daily.phase")p.daily.phase=std::stoi(v);else if(k=="daily.loop")p.daily.loop=std::stoi(v);else if(k=="daily.time")p.daily.time=std::stod(v);else if(k=="daily.victory")p.daily.victory=v=="1";}catch(...){}}return p;}
bool saveProfile(const Profile&p,const std::string&path){std::ofstream f(path,std::ios::trunc);if(!f)return false;f<<"coins="<<p.coins<<"\ninvested="<<p.invested<<"\n";for(auto&[id,_]:costs()){auto it=p.upgrades.rank.find(id);f<<"upgrade."<<id<<'='<<(it==p.upgrades.rank.end()?0:it->second)<<'\n';}for(auto&[sec,ids]:p.codex){f<<"codex."<<sec<<'=';bool first=true;for(auto&id:ids){if(!first)f<<',';first=false;f<<id;}f<<'\n';}f<<"daily.key="<<p.daily.key<<"\ndaily.phase="<<p.daily.phase<<"\ndaily.loop="<<p.daily.loop<<"\ndaily.time="<<p.daily.time<<"\ndaily.victory="<<(p.daily.victory?1:0)<<'\n';return (bool)f;}
int nextUpgradeCost(const std::string&id,int rank){auto it=costs().find(id);if(it==costs().end()||rank<0||rank>=(int)it->second.size())return -1;return it->second[rank];}
bool buyUpgrade(Profile&p,const std::string&id){int rank=p.upgrades.rank[id],cost=nextUpgradeCost(id,rank);if(cost<0||p.coins<cost)return false;p.coins-=cost;p.invested+=cost;p.upgrades.rank[id]=rank+1;return true;}
int respec(Profile&p){int refund=p.invested;p.coins+=refund;p.invested=0;p.upgrades.rank.clear();return refund;}void deposit(Profile&p,int amount){if(amount>0)p.coins+=amount;}
void observeCodex(Profile&p,const GameState&s,const Player*me){if(me)for(auto&[id,r]:me->powers)if(r>0)p.codex["powers"].insert(id);if(s.altar)p.codex["encounters"].insert("altar");if(s.encounter)p.codex["encounters"].insert(s.encounter->kind);for(auto&e:s.enemies)if(e.boss)p.codex["bosses"].insert(e.type);else p.codex["enemies"].insert(e.type);for(auto&ev:s.events){if(ev.kind=="convergence")p.codex["reactions"].insert("convergence");else if(ev.kind=="combo")p.codex["reactions"].insert("combo");else if(ev.kind=="bossDown"&&s.phase>=0&&s.phase<6)p.codex["bosses"].insert(phases()[s.phase].boss);}}
bool saveDailyIfBetter(Profile&p,const DailyRecord&c){if(p.daily.key!=c.key){p.daily=c;return true;}auto score=[](const DailyRecord&r){return std::tuple{r.victory?1:0,r.loop,r.phase,r.time};};if(score(c)>score(p.daily)){p.daily=c;return true;}return false;}
}
