#pragma once
#include "arcana/real.hpp"
namespace arcana::cfg {
constexpr int MAX_PLAYERS=4, MAX_ENEMIES=180, MAX_SHOTS=320, MAX_ENEMY_SHOTS=96, MAX_DROPS=220, MAX_HAZARDS=12, MAX_RUNES=24, MAX_ZONES=24;
constexpr real DROP_TTL=24, REVIVE_SECONDS=4, REVIVE_RADIUS=44, REVIVE_HEALTH=0.4;
constexpr real SPECIAL_MAX=100, SPECIAL_CRYSTAL=25, SPECIAL_COOLDOWN=8;
constexpr int SPECIAL_SHOTS=12;
constexpr real DASH_COOLDOWN=4, DASH_SECONDS=.18, DASH_SPEED=850;
constexpr real POWER_TIMEOUT=15, INVULN_AFTER_CHOICE=3;
constexpr real CONTACT_SCALE=.73, CONTACT_ENEMY_COOLDOWN=.8, CONTACT_PLAYER_COOLDOWN=.1, CONTACT_RADIUS=34;
constexpr real DROP_HEART=.05, DROP_GREEN=.2, DROP_COIN=.03, DROP_MERGE_AT=140, DROP_MERGE_RADIUS=90, MAGNET_SPEED=620, PICKUP_SPEED=350, COLLECT_RADIUS=24;
constexpr real ELITE_HP=7, ELITE_DAMAGE=1.5, ELITE_SPEED=.9, ELITE_XP=6;
constexpr real EVENT_WINDOW=1.5;
}
